set_property IOSTANDARD LVCMOS33 [get_ports LCD_E]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RW]
set_property IOSTANDARD LVCMOS33 [get_ports btn_1]
set_property IOSTANDARD LVCMOS33 [get_ports btn_2]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_W_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_Y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_Y[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_Y[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_Y[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]

set_property PACKAGE_PIN Y1 [get_ports rst]

set_property PACKAGE_PIN W3 [get_ports {switch[2]}]
set_property PACKAGE_PIN U2 [get_ports {switch[1]}]
set_property PACKAGE_PIN T1 [get_ports {switch[0]}]

set_property PACKAGE_PIN K4 [get_ports btn_1]
set_property PACKAGE_PIN N8 [get_ports btn_2]

set_property PACKAGE_PIN B6 [get_ports clk]
set_property PACKAGE_PIN A6 [get_ports LCD_E]
set_property PACKAGE_PIN G6 [get_ports LCD_RS]
set_property PACKAGE_PIN D6 [get_ports LCD_RW]

set_property PACKAGE_PIN D1 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN C1 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN C5 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN A2 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN D4 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN C3 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN B2 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN A4 [get_ports {LCD_DATA[0]}]

set_property PACKAGE_PIN E16 [get_ports {led_G[3]}] 
set_property PACKAGE_PIN C16 [get_ports {led_G[2]}] 
set_property PACKAGE_PIN A20 [get_ports {led_G[1]}] 
set_property PACKAGE_PIN E11 [get_ports {led_G[0]}] 

set_property PACKAGE_PIN F15 [get_ports {led_left[3]}] 
set_property PACKAGE_PIN D15 [get_ports {led_left[2]}] 
set_property PACKAGE_PIN C19 [get_ports {led_left[1]}] 
set_property PACKAGE_PIN F10 [get_ports {led_left[0]}] 

set_property PACKAGE_PIN B13 [get_ports {led_R[3]}]
set_property PACKAGE_PIN G14 [get_ports {led_R[2]}] 
set_property PACKAGE_PIN C17 [get_ports {led_R[1]}] 
set_property PACKAGE_PIN C12 [get_ports {led_R[0]}] 

set_property PACKAGE_PIN E19 [get_ports {led_W_G[3]}]
set_property PACKAGE_PIN F12 [get_ports {led_W_G[2]}] 
set_property PACKAGE_PIN A16 [get_ports {led_W_G[1]}] 
set_property PACKAGE_PIN G11 [get_ports {led_W_G[0]}] 

set_property PACKAGE_PIN A19 [get_ports {led_W_R[3]}]
set_property PACKAGE_PIN G13 [get_ports {led_W_R[2]}] 
set_property PACKAGE_PIN E18 [get_ports {led_W_R[1]}]
set_property PACKAGE_PIN C11 [get_ports {led_W_R[0]}]

set_property PACKAGE_PIN L18 [get_ports {led_Y[3]}]
set_property PACKAGE_PIN A14 [get_ports {led_Y[2]}] 
set_property PACKAGE_PIN C18 [get_ports {led_Y[1]}] 
set_property PACKAGE_PIN D13 [get_ports {led_Y[0]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]